# Generated by Django 6.0 on 2025-12-09 23:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TileRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tile', models.CharField(db_index=True, max_length=8)),
                ('start_date', models.CharField(max_length=8)),
                ('end_date', models.CharField(max_length=8)),
                ('source', models.CharField(choices=[('fc', 'FC'), ('sr', 'SR')], default='fc', max_length=4)),
                ('veg_index', models.CharField(blank=True, max_length=8, null=True)),
                ('savi_L', models.FloatField(blank=True, null=True)),
                ('span_years', models.IntegerField(default=10)),
                ('window_start', models.CharField(blank=True, max_length=4, null=True)),
                ('window_end', models.CharField(blank=True, max_length=4, null=True)),
                ('sr_dir_start', models.CharField(blank=True, max_length=512, null=True)),
                ('sr_dir_end', models.CharField(blank=True, max_length=512, null=True)),
                ('omit_start_threshold', models.BooleanField(default=False)),
                ('collect_logs', models.BooleanField(default=True)),
                ('status', models.CharField(default='queued', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('log_path', models.CharField(blank=True, max_length=512, null=True)),
                ('dll_path', models.CharField(blank=True, max_length=512, null=True)),
                ('dlj_path', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
