# Generated by Django 6.0 on 2025-12-15 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EDSResult",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "visual_check",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("analyst", models.CharField(blank=True, max_length=10, null=True)),
                ("comments", models.TextField(blank=True, null=True)),
                ("shp_path", models.TextField(blank=True, null=True)),
                ("cleared", models.IntegerField(default=0)),
                ("not_cleared", models.IntegerField(default=0)),
                (
                    "supplied_to_ceb",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("start_date", models.CharField(blank=True, max_length=8, null=True)),
                ("end_date", models.CharField(blank=True, max_length=8, null=True)),
                ("start_date_dt", models.DateTimeField(blank=True, null=True)),
                ("end_date_dt", models.DateTimeField(blank=True, null=True)),
                ("path", models.IntegerField()),
                ("row", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "eds_results",
                "ordering": ["-created_at"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="EDSRun",
            fields=[
                (
                    "run_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("run_number", models.IntegerField(unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "eds_runs",
                "ordering": ["-run_number"],
                "managed": False,
            },
        ),
    ]
