# Generated by Django 6.0 on 2025-12-15 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QCAuditLog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("action", models.CharField(max_length=50)),
                ("old_value", models.TextField(blank=True, null=True)),
                ("new_value", models.TextField(blank=True, null=True)),
                ("changed_by", models.CharField(max_length=255)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("change_reason", models.TextField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "db_table": "qc_audit_log",
                "ordering": ["-changed_at"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="QCValidation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("tile_id", models.CharField(db_index=True, max_length=20)),
                (
                    "qc_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("rejected", "Rejected"),
                            ("requires_review", "Requires Review"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "reviewed_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("is_confirmed_clearing", models.BooleanField(blank=True, null=True)),
                (
                    "confidence_score",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "⭐ Very Low"),
                            (2, "⭐⭐ Low"),
                            (3, "⭐⭐⭐ Medium"),
                            (4, "⭐⭐⭐⭐ High"),
                            (5, "⭐⭐⭐⭐⭐ Very High"),
                        ],
                        null=True,
                    ),
                ),
                ("reviewer_comments", models.TextField(blank=True, null=True)),
                ("validation_notes", models.TextField(blank=True, null=True)),
                ("requires_field_visit", models.BooleanField(default=False)),
                (
                    "priority_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "qc_validations",
                "ordering": ["-created_at"],
                "managed": False,
            },
        ),
    ]
