# Generated by Django 6.0 on 2025-12-15 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DetectionAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alert_id", models.CharField(max_length=255, unique=True)),
                ("job_id", models.CharField(max_length=255)),
                ("tile_id", models.CharField(max_length=20)),
                ("detection_lat", models.FloatField()),
                ("detection_lon", models.FloatField()),
                ("detection_geojson", models.TextField(blank=True, null=True)),
                ("detection_date", models.DateTimeField()),
                ("confidence_score", models.FloatField()),
                ("area_hectares", models.FloatField()),
                (
                    "clearing_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("severity", models.CharField(blank=True, max_length=50, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "verification_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "verified_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("verification_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "detection_alerts",
                "ordering": ["-detection_date"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="EDSDetection",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("properties", models.TextField(blank=True, null=True)),
                ("geom_geojson", models.TextField(blank=True, null=True)),
                ("geom_wkt", models.TextField(blank=True, null=True)),
                (
                    "geom_hash",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True, unique=True
                    ),
                ),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "eds_detections",
                "ordering": ["-imported_at"],
                "managed": False,
            },
        ),
    ]
