# Generated by Django 6.0 on 2025-12-15 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LandsatTile",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tile_id",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("path", models.IntegerField(db_index=True)),
                ("row", models.IntegerField(db_index=True)),
                ("center_lat", models.FloatField()),
                ("center_lon", models.FloatField()),
                ("bounds_geojson", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(db_index=True, default="pending", max_length=20),
                ),
                (
                    "last_processed",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processing_priority", models.IntegerField(default=5)),
                ("is_active", models.BooleanField(default=True)),
                ("processing_notes", models.TextField(blank=True, null=True)),
                ("latest_landsat_date", models.DateTimeField(blank=True, null=True)),
                ("data_quality_score", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "landsat_tiles",
                "ordering": ["path", "row"],
                "managed": False,
            },
        ),
    ]
